name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'true'  # Ensures submodules are checked out

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build app
        run: npm run build

      - name: Push changes (if applicable)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git push origin main  # Push to GitHub if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
